print("Aplikasi Steganografi")
print("1: Penyisipan pesan")
print("2: Ekstraksi pesan")
print("Pilih (1/2/3): ")

print("Penyisipan Pesan")
print("1: Audio")
print("2: Video")
print("3: Kembali")
print("Pilih (1/2/3): ")

print("Masukkan file audio:")
print("File audio: ")
print("1: Mainkan file audio")
print("2: Sisipkan pesan secara sekuensial")
print("3: Sisipkan pesan secara acak")
print("4: Kembali")
print("Pilih (1/2/3/4): ")

print("Masukkan kunci: ")
print("Masukkan file eksternal: ")
print("Simpan file audio dengan nama:")
print("Audio hasil sisipan pesan berhasil dibuat")
print("Mainkan hasil file audio? (y/n)")

print("Ekstraksi Pesan")
print("1: Audio")
print("2: Video")
print("3: Kembali")
print("Pilih (1/2/3): ")

print("Masukkan file audio:")
print("File audio: ")
print("1: Mainkan file audio")
print("2: Ekstraksi pesan ke file eksternal")
print("3: Ekstraksi pesan langsung")
print("4: Kembali")
print("Pilih (1/2/3/4): ")